import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server';
import { ConvexClientProvider } from '@/components/ConvexClientProvider';
const inter = Inter({ subsets: ['latin'] });

import { Toaster } from 'react-hot-toast';
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ConvexAuthNextjsServerProvider>
			<html lang='en'>
				<body className={inter.className}>
					<ConvexClientProvider>
						{children} <Toaster position='top-right' />
					</ConvexClientProvider>
				</body>
			</html>
		</ConvexAuthNextjsServerProvider>
	);
}
